<?php
// Datos geográficos del Ecuador
$provincias_ecuador = [
    'AZUAY' => [
        'CUENCA' => ['CUENCA', 'BAÑOS', 'CHECA', 'CHIQUINTAD', 'LLACAO', 'MOLLETURO', 'NULTI', 'OCTAVIO CORDERO PALACIOS', 'PACCHA', 'QUINGEO', 'RICARTE', 'SAN JOAQUÍN', 'SANTA ANA', 'SAYAUSÍ', 'SIDCAY', 'SININCAY', 'TARQUI', 'TURI', 'VALLE', 'VICTORIA DEL PORTETE', 'VIRGEN DE FÁTIMA'],
        'GIRÓN' => ['GIRÓN', 'ASUNCIÓN', 'SAN GERARDO'],
        'GUALACEO' => ['GUALACEO', 'CHORDELEG', 'DANIEL CÓRDOVA TORAL', 'JADÁN', 'MARIANO MORENO', 'REMIGIO CRESPO TORAL', 'SAN JUAN', 'ZHIDMAD', 'LUIS CORDERO VEGA', 'SIMÓN BOLÍVAR', 'ZHAGLLI', 'SHUARO'],
        'NABÓN' => ['NABÓN', 'COCHAPATA', 'EL PROGRESO', 'LAS NIEVES', 'OÑA'],
        'PAUTE' => ['PAUTE', 'AMALUZA', 'BULÁN', 'CHICÁN', 'EL CABO', 'GUACHAPALA', 'GUARAINAG', 'PALMAS', 'PAN', 'PUCARÁ', 'SAN CRISTÓBAL', 'SEVILLA DE ORO', 'TOMEBAMBA', 'DUG DUG'],
        'PUCARÁ' => ['PUCARÁ', 'CAMILO PONCE ENRÍQUEZ', 'CHIQUINTAD', 'EL VALLE', 'SAN FERNANDO'],
        'SAN FERNANDO' => ['SAN FERNANDO', 'CHUMBLÍN'],
        'SANTA ISABEL' => ['SANTA ISABEL', 'ABDÓN CALDERÓN', 'EL CARMEN DE PIJILÍ', 'ZHAGLLI'],
        'SEVILLA DE ORO' => ['SEVILLA DE ORO', 'AMALUZA', 'PALMAS'],
        'SÍGSIG' => ['SÍGSIG', 'GUALLETURO', 'SAN BARTOLOMÉ', 'SAN JOSÉ DE RARANGA', 'SAN FELIPE DE OÑA', 'SIGSIG'],
        'OÑA' => ['OÑA', 'SUSUDEL']
    ],
    'BOLÍVAR' => [
        'GUARANDA' => ['GUARANDA', 'GABRIEL GARCÍA MORENO', 'GUARANDA', 'GUANUJO', 'FACUNDO VELA', 'GUARANDA', 'SALINAS', 'SAN LORENZO', 'SAN MIGUEL', 'SAN PABLO DE ATENAS', 'SAN VICENTE'],
        'CHILLANES' => ['CHILLANES', 'SAN JOSÉ DEL TAMBO'],
        'CHIMBO' => ['CHIMBO', 'ASUNCIÓN', 'CALUMA', 'MAGDALENA', 'SAN SEBASTIÁN'],
        'ECHEANDÍA' => ['ECHEANDÍA'],
        'SAN MIGUEL' => ['SAN MIGUEL', 'BALSAPAMBA', 'BILOVÁN', 'REGULO DE MORA', 'SAN PABLO', 'SANTIAGO', 'SAN VICENTE'],
        'CALUMA' => ['CALUMA'],
        'LAS NAVES' => ['LAS NAVES', 'AURELIO ESPINOZA PÓLIT']
    ],
    'CAÑAR' => [
        'AZOGUES' => ['AZOGUES', 'BIBLIAN', 'CAÑAR', 'COJITAMBO', 'DÉLEG', 'EL TAMBO', 'LA TRONCAL', 'SUSCAL'],
        'BIBLIÁN' => ['BIBLIÁN', 'JERUSALÉN'],
        'CAÑAR' => ['CAÑAR', 'CHONTAMARCA', 'CHOROCÓPTE', 'GENERAL MORALES', 'GUALLETURO', 'HONORATO VÁSQUEZ', 'INGAPIRCA', 'JUNCAL', 'SAN ANTONIO', 'SUSCAL'],
        'LA TRONCAL' => ['LA TRONCAL', 'MANUEL J. CALLE'],
        'EL TAMBO' => ['EL TAMBO', 'DÉLEG'],
        'DÉLEG' => ['DÉLEG', 'SOLANO']
    ],
    'CARCHI' => [
        'TULCÁN' => ['TULCÁN', 'EL CARMELO', 'JULIO ANDRADE', 'MALDONADO', 'PIOTER', 'TOBAR DONOSO', 'URBINA'],
        'BOLÍVAR' => ['BOLÍVAR', 'GARCÍA MORENO'],
        'ESPEJO' => ['ESPEJO', 'EL ÁNGEL', 'LA LIBERTAD', 'SAN ISIDRO'],
        'MIRA' => ['MIRA', 'CONCEPCIÓN', 'JIJÓN Y CAAMAÑO', 'JUAN MONTALVO'],
        'MONTÚFAR' => ['MONTÚFAR', 'CRISTÓBAL COLÓN', 'CHITÁN DE NAVARRETE', 'FERNÁNDEZ SALVADOR', 'LA PAZ', 'PIARTAL'],
        'SAN PEDRO DE HUACA' => ['SAN PEDRO DE HUACA']
    ],
    'CHIMBORAZO' => [
        'RIOBAMBA' => ['RIOBAMBA', 'CACHA', 'CALPI', 'CUBIJÍES', 'FLORES', 'LICAN', 'LICTO', 'PUNGALA', 'PUNÍN', 'QUIMIAG', 'SAN ANDRÉS', 'SAN JUAN', 'SAN LUIS'],
        'ALAUSÍ' => ['ALAUSÍ', 'ACHUPALLAS', 'CUMANDÁ', 'GUASUNTOS', 'HUIGRA', 'MULTITUD', 'PISTISHÍ', 'PUMALLACTA', 'SEVILLA'],
        'COLTA' => ['COLTA', 'CAJABAMBA', 'CAÑI', 'COLUMBE', 'JUAN DE VELASCO', 'SANTIAGO DE QUITO', 'SICALPA'],
        'CHAMBO' => ['CHAMBO'],
        'CHUNCHI' => ['CHUNCHI', 'CAPZOL', 'COMPUD', 'GONZOL', 'LLAGOS'],
        'GUAMOTE' => ['GUAMOTE', 'CEBADAS', 'PALMIRA'],
        'GUANO' => ['GUANO', 'LA ASUNCIÓN', 'ILAPO', 'SAN ANDRÉS', 'SAN GERARDO DE PACAICAGUAN', 'SAN ISIDRO DE PATULÚ', 'SAN JOSÉ DEL CHAZO', 'SANTA FE DE GALÁN', 'VALPARAÍSO'],
        'PALLATANGA' => ['PALLATANGA'],
        'PENIPE' => ['PENIPE', 'EL ALTAR', 'MATUS', 'PUELA', 'SAN ANDRÉS', 'BILBAO', 'LA CANDELARIA'],
        'CUMANDÁ' => ['CUMANDÁ']
    ],
    'COTOPAXI' => [
        'LATACUNGA' => ['LATACUNGA', 'ALAQUES', 'BELISARIO QUEVEDO', 'GUAYTACAMA', 'JOSEGUANGO BAJO', 'LAS PAMPAS', 'MULALÓ', '11 DE NOVIEMBRE', 'POALÓ', 'SAN JUAN DE PASTOCALLE', 'SIGCHOS', 'TANICUCHÍ', 'TOACASO', 'PILALÓ'],
        'LA MANÁ' => ['LA MANÁ', 'EL CORAZÓN', 'MORASPUNGO'],
        'PANGUA' => ['PANGUA', 'EL TRIUNFO', 'LA MATRIZ', 'PISHILATA', 'RAMÓN CAMPAÑA'],
        'PUJILÍ' => ['PUJILÍ', 'ANGAMARCA', 'CHUCCHILÁN', 'JUAN MONTALVO', 'LA MATRIZ', 'SAN MIGUEL', 'ZUMBAHUA'],
        'SALCEDO' => ['SALCEDO', 'CUSUBAMBA', 'MULALILLO', 'PANCHALÍ'],
        'SAQUISILÍ' => ['SAQUISILÍ', 'CANCHAGUA', 'CHANTILÍN', 'COCHAPAMBA', 'EL ROSARIO', 'GUASAGANDA', 'PILALÓ'],
        'SIGCHOS' => ['SIGCHOS', 'CHUGCHILÁN', 'ISINLIVÍ', 'LAS PAMPAS', 'PALO QUEMADO', 'SAN MIGUEL DE POROTOS', 'TANICUCHÍ']
    ],
    'EL ORO' => [
        'MACHALA' => ['MACHALA', 'EL CAMBIO', 'LA PROVIDENCIA', '9 DE MAYO', 'PUERTO BOLÍVAR'],
        'ARENILLAS' => ['ARENILLAS', 'CHACRAS', 'PALMALES', 'CARCABÓN', 'LA LIBERTAD', 'LAS LAJAS', 'PACCHA', 'SAN ANTONIO', 'SANTA ROSA'],
        'ATAHUALPA' => ['ATAHUALPA', 'PACCHA'],
        'BALSAS' => ['BALSAS', 'BELLAVISTA'],
        'CHILLA' => ['CHILLA'],
        'EL GUABO' => ['EL GUABO', 'BARBONES', 'LA IBERIA', 'TENDALES', 'RÍO BONITO'],
        'HUAQUILLAS' => ['HUAQUILLAS', 'HUALTACO', 'MARCABELÍ', 'EL PARAÍSO'],
        'LAS LAJAS' => ['LAS LAJAS', 'LA VICTORIA'],
        'MARCABELÍ' => ['MARCABELÍ', 'EL INGA'],
        'PASAJE' => ['PASAJE', 'BUENAVISTA', 'CASACAY', 'LA PEAÑA', 'PROGRESO', 'UZHCURRUMI', 'CAÑAQUEMADA', 'MERCADILLO', 'OCHOA LEÓN'],
        'PIÑAS' => ['PIÑAS', 'CAPIRO', 'LA BOCANA', 'MOROMORO', 'PIEDRAS', 'SAN ROQUE', 'SARACAY'],
        'PORTOVELO' => ['PORTOVELO', 'CURTINCAPA', 'MORALES', 'SALATÍ'],
        'SANTA ROSA' => ['SANTA ROSA', 'BELLAVISTA', 'JAMBELÍ', 'LA AVANZADA', 'SAN ANTONIO', 'TORATA', 'VICTORIA'],
        'ZARUMA' => ['ZARUMA', 'ARCAPAMBA', 'GUANAZÁN', 'HUERTAS', 'MALVAS', 'MULUNCAY GRANDE', 'SINCHE', 'UZHCURRUMI']
    ],
    'ESMERALDAS' => [
        'ESMERALDAS' => ['ESMERALDAS', 'ATACAMES', 'ELOY ALFARO', 'MUISNE', 'QUININDÉ', 'ROSA ZÁRATE', 'SAN MATEO', 'SÚA', 'TABIAZO', 'TACHINA', 'TONCHIGÜE', 'VUELTA LARGA'],
        'ELOY ALFARO' => ['ELOY ALFARO', 'BORBÓN', 'LA TOLA', 'LUIS VARGAS TORRES', 'MALDONADO', 'PAMPANAL DE BOLÍVAR', 'SAN FRANCISCO DE ONZOLE', 'VALDEZ'],
        'MUISNE' => ['MUISNE', 'BOLÍVAR', 'DAULE', 'GALERA', 'QUINGUE', 'SALIMA', 'SAN GREGORIO', 'SAN JOSÉ DE CHAMANGA', 'TONGORACHÍ'],
        'QUININDÉ' => ['QUININDÉ', 'LA CONCORDIA', 'MALIMPIA', 'VICHE'],
        'ROSA ZÁRATE' => ['ROSA ZÁRATE', 'CUBE', 'CHURA', 'MATAJE', 'SAN LORENZO', 'TAMBILLO'],
        'SAN LORENZO' => ['SAN LORENZO', 'ALTO TAMBO', 'ANCÓN', 'CALDERÓN', 'CARONDELÉT', '5 DE JUNIO', 'CONCEPCIÓN', 'MATAJE', 'SAN JAVIER DE CACHAVÍ', 'SANTA RITA', 'SELVA ALEGRE', 'TAMBILLO', 'TULULBÍ', 'URBINA']
    ],
    'GALÁPAGOS' => [
        'SAN CRISTÓBAL' => ['PUERTO BAQUERIZO MORENO', 'EL PROGRESO', 'ISLA SANTA MARÍA', 'PUERTO VILLAMIL'],
        'SANTA CRUZ' => ['PUERTO AYORA', 'BELLAVISTA', 'SANTA ROSA'],
        'ISABELA' => ['PUERTO VILLAMIL', 'TOMÁS DE BERLANGA', 'EL PROGRESO']
    ],
    'GUAYAS' => [
        'GUAYAQUIL' => ['GUAYAQUIL', 'CHONGÓN', 'PASCUALES', 'TARQUI', 'TENGUEL', 'XIMENA'],
        'ALFREDO BAQUERIZO MORENO' => ['JUJAN', 'PALENQUE'],
        'BALAO' => ['BALAO'],
        'BALZAR' => ['BALZAR'],
        'COLIMES' => ['COLIMES', 'SAN JACINTO'],
        'DAULE' => ['DAULE', 'LA AURORA', 'BANIFE', 'EMILIO ESTRADA', 'MARCELINO MARIDUEÑA', 'SAN CARLOS', 'SANTA CLARA'],
        'DURÁN' => ['DURÁN', 'ELOY ALFARO', 'EL RECREO'],
        'EL TRIUNFO' => ['EL TRIUNFO', 'VALENCIA'],
        'EMPAMLE' => ['EMPALME', 'VELASCO IBARRA'],
        'EL EMPALME' => ['EL EMPALME', 'VELASCO IBARRA'],
        'MILAGRO' => ['MILAGRO', 'CHOBO', 'MARISCAL SUCRE', 'ROBERTO ASTUDILLO'],
        'NARANJAL' => ['NARANJAL', 'JESÚS MARÍA', 'SAN CARLOS', 'SANTA ROSA DE FLANDES', 'TAURA'],
        'NARANJITO' => ['NARANJITO'],
        'NOBOL' => ['NOBOL', 'NARCISA DE JESÚS'],
        'PALESTINA' => ['PALESTINA'],
        'PEDRO CARBO' => ['PEDRO CARBO', 'SAMBORONDÓN'],
        'PLAYAS' => ['PLAYAS', 'GENERAL VILLAMIL'],
        'SALITRE' => ['SALITRE', 'BOCA DE CAÑA', 'GENERAL VERNAZA'],
        'SAMBORONDÓN' => ['SAMBORONDÓN', 'LA PUNTILLA'],
        'SANTA LUCÍA' => ['SANTA LUCÍA'],
        'SIMÓN BOLÍVAR' => ['SIMÓN BOLÍVAR'],
        'YAGUACHI' => ['YAGUACHI', 'GENERAL ANTONIO ELIZALDE', 'ISIDRO AYORA', 'MARCELINO MARIDUEÑA', 'ROBERTO ASTUDILLO', 'SAN JACINTO DE YAGUACHI', 'VIRGEN DE FÁTIMA']
    ],
    'IMBABURA' => [
        'IBARRA' => ['IBARRA', 'AMBUQUÍ', 'ANDRADE MARÍN', 'ATUNTAQUI', 'BOLÍVAR', 'CARPUELA', 'LA ESPERANZA', 'LITA', 'SALINAS', 'SAN ANTONIO DE IBARRA'],
        'ANTONIO ANTE' => ['ATUNTAQUI', 'ANDRADE MARÍN', 'SAN FRANCISCO DE NATABUELA'],
        'COTACACHI' => ['COTACACHI', 'APUELA', 'GARCÍA MORENO', 'IMANTAG', 'PEÑAHERRERA', 'PLAZA GUTIÉRREZ', 'QUIROGA', '6 DE JULIO DE CUELLAJE', 'VACAS GALINDO'],
        'OTAVALO' => ['OTAVALO', 'ANCÓN', 'EUGENIO ESPEJO', 'GONZÁLEZ SUÁREZ', 'PEGUCHE', 'QUINCHISÚQUÍ', 'SAN PABLO DEL LAGO', 'SELVA ALEGRE', 'DR. MIGUEL EGAS CABEZAS'],
        'PIMAMPIRO' => ['PIMAMPIRO', 'CHUGÁ', 'MARIANO ACOSTA', 'SAN FRANCISCO DE SIGSIPAMBA'],
        'SAN MIGUEL DE URCUQUÍ' => ['URCUQUÍ', 'CAHUASQUÍ', 'LA MERCED DE BUENOS AIRES', 'PABLO ARENAS', 'SAN BLAS', 'TUMBABIRO']
    ],
    'LOJA' => [
        'LOJA' => ['LOJA', 'CHANTACO', 'CHUQUIRIBAMBA', 'EL CISNE', 'GUALEL', 'JIMBILLA', 'MALACATOS', 'SAN LUCAS', 'SAN PEDRO DE VILCABAMBA', 'SANTIAGO', 'TAQUIL', 'VILCABAMBA', 'YANGANA'],
        'CALVAS' => ['CARIAMANGA', 'CHILE', 'COLAISACA', 'EL LUCERO', 'UTUANA', 'SANGUILLÍN'],
        'CATAMAYO' => ['CATAMAYO', 'EL TAMBO', 'GUAYQUICHUMA', 'SAN PEDRO DE LA BENDITA', 'ZAMBI'],
        'CELICA' => ['CELICA', 'CRUZPAMBA', 'CHAUCHA', '12 DE DICIEMBRE', 'PINDAL', 'POALÓ', 'SABANILLA'],
        'CHAGUARPAMBA' => ['CHAGUARPAMBA', 'BUENAVISTA', 'EL ROSARIO', 'SANTA RUFINA', 'AMARILLOS'],
        'ESPÍNDOLA' => ['AMALUZA', 'BELLAVISTA', 'JIMBURA', 'SANTA TERESITA', '27 DE ABRIL'],
        'GONZANAMÁ' => ['GONZANAMÁ', 'CHANGAIMINA', 'FUNDOCHAMBA', 'NAMBACOLA', 'PURUNUMA', 'QUILANGA', 'SACAPALCA', 'SAN ANTONIO DE LAS ARADAS', 'ZAPOTILLO'],
        'MACARÁ' => ['MACARÁ', 'EL AIRO', 'SAN ANTONIO', 'SAN VICENTE'],
        'OLMEDO' => ['OLMEDO', 'LA TOMA'],
        'PALTAS' => ['CATACOCHA', 'CANGONAMÁ', 'GUACHANAMÁ', 'LA TINGUE', 'LAURO GUERRERO', 'OLMEDO', 'ORIANGA', 'SAN ANTONIO', 'CASANGA', 'YAMANA'],
        'PINDAL' => ['PINDAL', '12 DE DICIEMBRE', 'CHAUCHA', 'SABANILLA'],
        'PUYANGO' => ['ALAMOR', 'CIANO', 'EL AIRO', 'ORIANGA', 'SAN ANTONIO', 'SAN VICENTE DE CANEY', 'VICENTE'],
        'QUILANGA' => ['QUILANGA', 'FUNDOCHAMBA', 'SAN ANTONIO DE LAS ARADAS'],
        'SARAGURO' => ['SARAGURO', 'EL PARAÍSO DE CELÉN', 'MANÚ', 'SAN ANTONIO DE QUILANGA', 'TENTA', 'URDANETA', 'SUMAYPAMBA'],
        'SOZORANGA' => ['SOZORANGA', 'NUEVA FÁTIMA', 'EL MÉTODO', 'EL ROSARIO'],
        'ZAPOTILLO' => ['ZAPOTILLO', 'CAZADEROS', 'GARZA REAL', 'LIMONES', 'PALETILLAS', 'SAN ANTONIO', 'BOLASPAMBA']
    ],
    'LOS RÍOS' => [
        'BABAHOYO' => ['BABAHOYO', 'BARREIRO', 'CARACOL', 'FEBRESCORDERO', 'PIMOCHA', 'LA UNIÓN', 'MONTALVO', 'PUEBLOVIEJO', 'PUERTO PECHICHE', 'SAN JUAN', 'TAURA'],
        'BABA' => ['BABA', 'GUARE', 'ISLA DE BEJUCAL'],
        'MONTALVO' => ['MONTALVO', 'LA UNIÓN'],
        'PUEBLOVIEJO' => ['PUEBLOVIEJO', 'PUERTO PECHICHE', 'SAN JUAN'],
        'QUEVEDO' => ['QUEVEDO', 'LA ESPERANZA', 'MOCACHE', 'SAN CARLOS', 'VALENCIA'],
        'URDANETA' => ['CATARAMA', 'RICAURTE'],
        'VENTANAS' => ['VENTANAS', 'QUINSALOMA', 'ZAPOTAL'],
        'VÍNCES' => ['VÍNCES', 'ANTONIO SOTOMAYOR', 'PALESTINA', 'PALENQUE', 'PUEBLO NUEVO']
    ],
    'MANABÍ' => [
        'PORTOVIEJO' => ['PORTOVIEJO', 'ALHAJUELA', 'CALCETA', 'CHONE', 'EL CARMEN', 'FLAVIO ALFARO', 'JIPIJAPA', 'JUNÍN', 'MANTA', 'MONTECRISTI', 'PAJÁN', 'PICHINCHA', 'ROCAFUERTE', 'SANTA ANA', 'SUCRE', 'TOSAGUA', '24 DE MAYO'],
        'BOLÍVAR' => ['CALCETA', 'QUIROGA'],
        'CHONE' => ['CHONE', 'BOYACÁ', 'CANUTO', 'CONVENTO', 'CHIBUNGA', 'ELOY ALFARO', 'RICAURTE', 'SAN ANTONIO'],
        'EL CARMEN' => ['EL CARMEN', '4 DE DICIEMBRE', 'WILFRIDO LOOR MOREIRA'],
        'FLAVIO ALFARO' => ['FLAVIO ALFARO', 'SAN FRANCISCO DE NOVILLO'],
        'JIPIJAPA' => ['JIPIJAPA', 'AMBUQUÍ', 'DR. MIGUEL MORÁN LUCIO', 'LA UNIÓN', 'MANUEL INOCENCIO PARRALES Y GUALE', 'SAN LORENZO', 'SAN SEBASTIÁN'],
        'JUNÍN' => ['JUNÍN', 'SAN JOSÉ DE ANCÓN'],
        'MANTA' => ['MANTA', 'ELOY ALFARO', 'LEONIDAS PROAÑO', 'SAN MATEO', 'TARQUI', 'LOS ESTEROS'],
        'MONTECRISTI' => ['MONTECRISTI', 'EL AROMO', 'GENERAL ELIZALDE', 'LEONIDAS PROAÑO', 'JARAMIJÓ', 'LA PILA'],
        'PAJÁN' => ['PAJÁN', 'CAMPOZANO', 'CASCOL', 'GUALE', 'LASCANO'],
        'PICHINCHA' => ['PICHINCHA', 'BARRAGANETE', 'SAN SEBASTIÁN'],
        'PUERTO LÓPEZ' => ['PUERTO LÓPEZ', 'MACHALILLA', 'SALANGO'],
        'ROCAFUERTE' => ['ROCAFUERTE', 'SAN PLÁCIDO'],
        'SANTA ANA' => ['SANTA ANA', 'AYACUCHO', 'HONORATO VÁSQUEZ', 'LA UNIÓN', 'OLMEDO', 'SAN PABLO'],
        'SUCRE' => ['BAHÍA DE CARÁQUEZ', 'LEONIDAS PLAZA GUTIÉRREZ', 'SAN ISIDRO'],
        'TOSAGUA' => ['TOSAGUA', 'BACHILLERO', 'LOS ANGELES'],
        '24 DE MAYO' => ['SUCRE', 'BELLAVISTA', 'NOBOA', 'ARQ. SIXTO DURÁN BALLÉN']
    ],
    'MORONA SANTIAGO' => [
        'MACAS' => ['MACAS', 'ALSHI', 'CHIGUAZA', 'GENERAL PROAÑO', 'HUASAGA', 'LOGROÑO', 'SAN ANTONIO', 'SEVILLA', 'SUCÚA', 'TUTUPALI', 'YAUPI'],
        'GUALAQUIZA' => ['GUALAQUIZA', 'AMAZONAS', 'BERMEJO', 'EL IDEAL', 'GENERAL LEONIDAS PLAZA GUTIÉRREZ', 'INDANZA', 'SAN MIGUEL DE CONCHAY', 'SAN MIGUEL DE CUYES', 'SANTIAGO DE PANANZA'],
        'HUAMBOYA' => ['HUAMBOYA', 'CHONTADURO'],
        'LIMÓN INDANZA' => ['GENERAL LEONIDAS PLAZA GUTIÉRREZ', 'INDANZA', 'SAN ANTONIO', 'SAN MIGUEL DE CONCHAY', 'SAN MIGUEL DE CUYES'],
        'LOGROÑO' => ['LOGROÑO', 'YAUPI'],
        'MORONA' => ['MACAS', 'ALSHI', 'CHIGUAZA', 'GENERAL PROAÑO', 'HUASAGA', 'LOGROÑO', 'SAN ANTONIO', 'SEVILLA', 'SUCÚA', 'TUTUPALI', 'YAUPI'],
        'PABLO SEXTO' => ['PABLO SEXTO'],
        'PALORA' => ['PALORA', 'ARAPICOS', 'CUMANDÁ', 'HUAMBOYA', 'SANGAY'],
        'SAN JUAN BOSCO' => ['SAN JUAN BOSCO', 'SANTIAGO DE PANANZA'],
        'SANTIAGO' => ['SANTIAGO', 'SAN FRANCISCO DE ORENSE', 'TARQUI'],
        'SUCÚA' => ['SUCÚA', 'ASUNCIÓN', 'HUAMBI', 'SAN SEBASTIÁN', 'YAUPI'],
        'TAISHA' => ['TAISHA', 'HUASAGA', 'LOGROÑO', 'YAUPI'],
        'TIWINTZA' => ['SANTIAGO', 'SAN FRANCISCO DE ORENSE', 'TARQUI']
    ],
    'NAPO' => [
        'TENA' => ['TENA', 'AHUANO', 'CARLOS JULIO AROSEMENA TOLA', 'CHONTAPUNTA', 'MISAHUALLÍ', 'PANO', 'PUERTO MISAHUALLÍ', 'PUERTO NAPO', 'SAN JOSÉ DE PAYAMINO', 'TALAG', 'YASUNI'],
        'ARCHIDONA' => ['ARCHIDONA', 'COTUNDO', 'SAN PABLO DE USHPAYACU'],
        'EL CHACO' => ['EL CHACO', 'GONZALO DÍAZ DE PINEDA'],
        'QUIJOS' => ['BAEZA', 'COSANGA', 'CUYUJA', 'PAPALLACTA', 'SAN FRANCISCO DE BORJA'],
        'CARLOS JULIO AROSEMENA TOLA' => ['CARLOS JULIO AROSEMENA TOLA']
    ],
    'ORELLANA' => [
        'FRANCISCO DE ORELLANA' => ['COCA', 'DAYUMA', 'EL EDÉN', 'GARCÍA MORENO', 'INÉS ARANGO', 'LA BELLEZA', 'NUEVO PARAÍSO', 'SAN JOSÉ DE GUAYUSA', 'TARACOA', 'TIPUTINI', 'YASUNI'],
        'AGUARICO' => ['NUEVO ROCAFUERTE', 'CAPITÁN AUGUSTO RIVADENEIRA', 'CONONACO', 'SANTA MARÍA DE HUIRIRIMA', 'TIPUTINI'],
        'LA JOYA DE LOS SACHAS' => ['LA JOYA DE LOS SACHAS', 'ENOKANQUI', 'POMPEYA', 'SAN CARLOS', 'SAN SEBASTIÁN DEL COCA', 'SHUSHUFINDI', 'LAGO SAN PEDRO'],
        'LORETO' => ['LORETO', 'AVILA', 'HUAMONI', 'SAN JOSÉ DE PAYAMINO', 'SAN JOSÉ DE DAHUANO', 'SAN VICENTE DE HUATICOCHA']
    ],
    'PASTAZA' => [
        'PUYO' => ['PUYO', 'ARAJUNO', 'CANELOS', 'DIEZ DE AGOSTO', 'FATIMA', 'MADRE TIERRA', 'MONTALVO', 'POMONA', 'PUERTO NAPO', 'SANTA CLARA', 'SIMÓN BOLÍVAR', 'TARQUI', 'VERACRUZ'],
        'ARAJUNO' => ['ARAJUNO', 'CURARAY', 'NUEVO ROCAFUERTE'],
        'MERA' => ['MERA', 'MADRE TIERRA', 'SHELL'],
        'SANTA CLARA' => ['SANTA CLARA', 'DIEZ DE AGOSTO'],
        'PASTAZA' => ['PUYO', 'ARAJUNO', 'CANELOS', 'DIEZ DE AGOSTO', 'FATIMA', 'MADRE TIERRA', 'MONTALVO', 'POMONA', 'PUERTO NAPO', 'SANTA CLARA', 'SIMÓN BOLÍVAR', 'TARQUI', 'VERACRUZ']
    ],
    'PICHINCHA' => [
        'QUITO' => ['QUITO', 'ALANGASÍ', 'AMAGUAÑA', 'ATAHUALPA', 'CALACALÍ', 'CALDERÓN', 'CONOCOTO', 'CUMBAYÁ', 'CHAVEZPAMBA', 'CHECA', 'CHILIBULO', 'CHILLOGALLO', 'CHIMBACALLE', 'COCHAPAMBA', 'COMITÉ DEL PUEBLO', 'COTOCOLLAO', 'EL CONDADO', 'EL INCA', 'GUAMANÍ', 'GUÁPULO', 'IÑAQUITO', 'ITCHIMBÍA', 'JIPIJAPA', 'KENNEDY', 'LA ARGELIA', 'LA CAROLINA', 'LA ECUATORIANA', 'LA FERROVIARIA', 'LA FLORESTA', 'LA LIBERTAD', 'LA MENA', 'LA MERCED', 'LA PAZ', 'LA PRENSA', 'LA ROLDÓS', 'LA VICENTINA', 'LLANO CHICO', 'LOS CHILLOS', 'MARISCAL SUCRE', 'MENA DEL HIERRO', 'MERCADO MAYORISTA', 'MITAD DEL MUNDO', 'NAYÓN', 'NUEVA AURORA', 'OLLANTAYTAMBO', 'POMASQUI', 'PONCEANO', 'PUSUQUÍ', 'QUITUMBE', 'RUMIPAMBA', 'SAN ANTONIO', 'SAN BARTOLO', 'SAN BLAS', 'SAN CARLOS', 'SAN DIEGO', 'SAN FRANCISCO', 'SAN ISIDRO DEL INCA', 'SAN JUAN', 'SAN MARCOS', 'SAN ROQUE', 'SANTA BÁRBARA', 'SANTA PRISCA', 'SANGOLQUÍ', 'SOLANDA', 'TUMBACO', 'TURUBAMBA', 'VALLE DE LOS CHILLOS', 'ZÁMBIZA'],
        'CAYAMBE' => ['CAYAMBE', 'AYORA', 'CANGAHUA', 'OLMEDO', 'OTÓN', 'SAN JOSÉ DE AYORA'],
        'MEJÍA' => ['MACHACHI', 'ALÓAG', 'ALOASÍ', 'CUTUGLAGUA', 'EL CHAUPI', 'MANUEL CORNEJO ASTORGA', 'TAMBILLO', 'UYUMBICHO'],
        'PEDRO MONCAYO' => ['TABACUNDO', 'LA ESPERANZA', 'MALCHINGUÍ', 'TOCACHI', 'TUPIGACHI'],
        'RUMIÑAHUI' => ['SANGOLQUÍ', 'ALANGASÍ', 'AMAGUAÑA', 'CONOCOTO', 'LA MERCED', 'SAN PEDRO DE TABOADA'],
        'SAN MIGUEL DE LOS BANCOS' => ['SAN MIGUEL DE LOS BANCOS', 'MINDO', 'PEDRO VICENTE MALDONADO'],
        'PEDRO VICENTE MALDONADO' => ['PEDRO VICENTE MALDONADO'],
        'PUERTO QUITO' => ['PUERTO QUITO']
    ],
    'SANTA ELENA' => [
        'SANTA ELENA' => ['SANTA ELENA', 'ATAHUALPA', 'COLONCHE', 'CHANDUY', 'MANGLARALTO', 'SIMÓN BOLÍVAR'],
        'LA LIBERTAD' => ['LA LIBERTAD'],
        'SALINAS' => ['SALINAS', 'ANCONCITO', 'ATAHUALPA', 'BALLENITA', 'CHIPIPE', 'GENERAL VILLAMIL', 'JOSÉ LUIS TAMAYO', 'LA LIBERTAD', 'SAN LORENZO']
    ],
    'SANTO DOMINGO DE LOS TSÁCHILAS' => [
        'SANTO DOMINGO' => ['SANTO DOMINGO', 'ALLURIQUÍN', 'EL ESFUERZO', 'LA CONCORDIA', 'LA INDEPENDENCIA', 'LUZ DE AMÉRICA', 'SAN JACINTO DEL BÚA', 'VALLE HERMOSO'],
        'LA CONCORDIA' => ['LA CONCORDIA', 'MONTERREY', 'PLAN PILOTO']
    ],
    'SUCUMBÍOS' => [
        'NUEVA LOJA' => ['NUEVA LOJA', 'CASCALES', 'CUYABENO', 'DURENO', 'EL ENO', 'GONZALO PIZARRO', 'LAGO AGRIO', 'LUMBAQUI', 'PABLO SEXTO', 'PUERTO EL CARMEN DE PUTUMAYO', 'SAN PEDRO DE LOS COFANES', 'SHUSHUFINDI', 'TARAPOA'],
        'CASCALES' => ['CASCALES', 'EL DORADO DE CASCALES'],
        'CUYABENO' => ['TARAPOA', 'AGUAS NEGRAS', 'CUYABENO', 'SIETE DE JULIO'],
        'GONZALO PIZARRO' => ['GONZALO PIZARRO', 'EL REVENTADOR', 'LUMBAQUI', 'PUERTO LIBRE'],
        'LAGO AGRIO' => ['LAGO AGRIO', 'DURENO', 'GENERAL FARFÁN', 'PACAYACU', 'SAN ROQUE', 'SEIS DE NOVIEMBRE', 'SHUSHUFINDI'],
        'PUTUMAYO' => ['PUERTO EL CARMEN DE PUTUMAYO', 'CARMEN DE PUTUMAYO', 'ROSA FLORIDA'],
        'SHUSHUFINDI' => ['SHUSHUFINDI', 'LIMONCOCHA', 'PAÑACOCHA', 'SAN ROQUE', 'SIETE DE JULIO', 'TARAPOA']
    ],
    'TUNGURAHUA' => [
        'AMBATO' => ['AMBATO', 'ATAHUALPA', 'CELIANO MONGE', 'HUACHI CHICO', 'HUACHI LORETO', 'HUACHI PATUL', 'HUACHI SAN ANTONIO', 'IZAMBA', 'JUAN BENIGNO VELA', 'LA MATRIZ', 'LA MERCED', 'LA PENÍNSULA', 'MONTALVO', 'PASA', 'PICAIGUA', 'PILAHUÍN', 'QUISAPINCHA', 'SAN BARTOLOMÉ DE PINLLO', 'SAN FERNANDO', 'SANTA ROSA', 'TOTORAS', 'UNAMUNCHO'],
        'BAÑOS DE AGUA SANTA' => ['BAÑOS', 'LLIGUA', 'ULBA'],
        'CEVALLOS' => ['CEVALLOS', 'MOCHA'],
        'MOCHA' => ['MOCHA', 'PINGUILÍ'],
        'PATATE' => ['PATATE', 'EL TRIUNFO', 'LOS ANDES'],
        'PELILEO' => ['PELILEO', 'BENÍTEZ', 'HUAMBALÓ', 'SALASACA'],
        'PÍLLARO' => ['PÍLLARO', 'BAQUERIZO MORENO', 'EMILIO MARÍA TERÁN', 'MARCOS ESPINEL', 'PRESIDENTE URBINA', 'SAN ANDRÉS', 'SAN JOSÉ DE POALÓ', 'SAN MIGUELITO'],
        'QUERO' => ['QUERO', 'RUMIPAMBA'],
        'SAN PEDRO DE PELILEO' => ['SAN PEDRO DE PELILEO', 'GARCÍA MORENO', 'HUAMBALÓ'],
        'SANTIAGO DE PÍLLARO' => ['SANTIAGO DE PÍLLARO', 'BAQUERIZO MORENO', 'EMILIO MARÍA TERÁN', 'MARCOS ESPINEL', 'PRESIDENTE URBINA', 'SAN ANDRÉS', 'SAN JOSÉ DE POALÓ', 'SAN MIGUELITO'],
        'TISALEO' => ['TISALEO', 'QUINCHE']
    ],
    'ZAMORA CHINCHIPE' => [
        'ZAMORA' => ['ZAMORA', 'CUMBARATZA', 'GUADALUPE', 'IMBANA', 'SABANILLA', 'SAN CARLOS DE LAS MINAS', 'TIMBARA', 'ZUMBI'],
        'CENTINELA DEL CÓNDOR' => ['ZUMBI', 'PANGUINTZA'],
        'CHINCHIPE' => ['ZUMBA', 'CHITO', 'EL CHORRO', 'EL PORVENIR DEL CARMEN', 'LA CHONTA', 'LA PAZ', 'SAN ANDRÉS', 'TUNDAYME'],
        'EL PANGUI' => ['EL PANGUI', 'EL GUISMI', 'PACHICUTZA', 'TUNDAYME'],
        'NANGARITZA' => ['GUAYZIMI', '28 DE MAYO', 'NUEVA FÁTIMA', 'TUTUPALI'],
        'PALANDA' => ['PALANDA', 'EL PORVENIR DEL CARMEN', 'SAN FRANCISCO DEL VERGEL'],
        'PAQUISHA' => ['PAQUISHA', 'BELLAVISTA', 'NUEVO QUITO'],
        'YACUAMBI' => ['YACUAMBI', '28 DE MAYO', 'LA PAZ', 'TUTUPALI'],
        'YANTZAZA' => ['YANTZAZA', 'CHICAÑA', 'LOS ENCUENTROS']
    ]
];

// Función para obtener cantones de una provincia
function getCantones($provincia) {
    global $provincias_ecuador;
    if (isset($provincias_ecuador[$provincia])) {
        return array_keys($provincias_ecuador[$provincia]);
    }
    return [];
}

// Función para obtener parroquias de un cantón en una provincia
function getParroquias($provincia, $canton) {
    global $provincias_ecuador;
    if (isset($provincias_ecuador[$provincia][$canton])) {
        return $provincias_ecuador[$provincia][$canton];
    }
    return [];
}

// Función para obtener todas las provincias
function getProvincias() {
    global $provincias_ecuador;
    return array_keys($provincias_ecuador);
}
?>


